const functions = require("firebase-functions");
const admin = require("firebase-admin");

// Function to check for duplicate requests for a specific employee
exports.checkDuplicateRequests = functions
  .region("asia-east2")
  .https.onRequest(async (req, res) => {
    try {
      const db = admin.firestore();
      const employeeId = req.query.employeeId ? parseInt(req.query.employeeId) : 20;
      const date = req.query.date || '2026-01-05';

      // Get all requests for this employee without ordering
      const allSnapshot = await db.collection('timeAttendanceRequests')
        .where('EmployeeID', '==', employeeId)
        .get();

      const dateCount = {};
      const allRequests = [];
      const requestsForDate = [];
      
      allSnapshot.forEach(doc => {
        const data = doc.data();
        if (data.Date && data.Date.startsWith('2026-01')) {
          dateCount[data.Date] = (dateCount[data.Date] || 0) + 1;
          allRequests.push({
            id: doc.id,
            date: data.Date,
            status: data.Status,
            autoGenerated: data.AutoGenerated
          });
          
          // Check if this is the specific date we're looking for
          if (data.Date === date) {
            requestsForDate.push({
              id: doc.id,
              employee: `${data.LastName} ${data.FirstName}`,
              date: data.Date,
              status: data.Status,
              autoGenerated: data.AutoGenerated,
              createdAt: data.CreatedAt?.toDate()
            });
          }
        }
      });

      const duplicates = Object.entries(dateCount)
        .filter(([date, count]) => count > 1)
        .map(([date, count]) => ({ date, count }))
        .sort((a, b) => a.date.localeCompare(b.date));

      res.json({
        success: true,
        employeeId,
        specificDate: date,
        requestsForDate: requestsForDate,
        totalForDate: requestsForDate.length,
        isDuplicate: requestsForDate.length > 1,
        allJanuaryRequests: allRequests.length,
        duplicateDates: duplicates,
        dateCount: Object.fromEntries(
          Object.entries(dateCount).sort(([a], [b]) => a.localeCompare(b))
        )
      });

    } catch (error) {
      console.error('Error checking duplicates:', error);
      res.status(500).json({
        success: false,
        error: error.message
      });
    }
  });
