const admin = require('firebase-admin');
const serviceAccount = require('./munkh-zaisan-firebase-adminsdk-x2hsg-be6a02cce4.json');

admin.initializeApp({
  credential: admin.credential.cert(serviceAccount)
});

const db = admin.firestore();

async function checkDuplicates() {
  try {
    // Check for employee ID 20 on 2026-01-05
    const snapshot = await db.collection('timeAttendanceRequests')
      .where('EmployeeID', '==', 20)
      .where('Date', '==', '2026-01-05')
      .get();

    console.log(`\nFound ${snapshot.size} requests for Employee ID 20 on 2026-01-05:\n`);
    
    snapshot.forEach(doc => {
      const data = doc.data();
      console.log(`Doc ID: ${doc.id}`);
      console.log(`  Employee: ${data.LastName} ${data.FirstName}`);
      console.log(`  Date: ${data.Date}`);
      console.log(`  Status: ${data.Status}`);
      console.log(`  AutoGenerated: ${data.AutoGenerated}`);
      console.log(`  CreatedAt: ${data.CreatedAt?.toDate()}`);
      console.log('---');
    });

    // Also check all requests for employee ID 20 in January 2026
    const allSnapshot = await db.collection('timeAttendanceRequests')
      .where('EmployeeID', '==', 20)
      .orderBy('Date')
      .get();

    console.log(`\nTotal requests for Employee ID 20 in database: ${allSnapshot.size}\n`);
    
    const dateCount = {};
    allSnapshot.forEach(doc => {
      const data = doc.data();
      if (data.Date && data.Date.startsWith('2026-01')) {
        dateCount[data.Date] = (dateCount[data.Date] || 0) + 1;
      }
    });

    console.log('Requests by date:');
    Object.keys(dateCount).sort().forEach(date => {
      console.log(`  ${date}: ${dateCount[date]} request(s)${dateCount[date] > 1 ? ' ⚠️ DUPLICATE' : ''}`);
    });

  } catch (error) {
    console.error('Error checking duplicates:', error);
  }
}

checkDuplicates();
