const functions = require("firebase-functions");
const admin = require("firebase-admin");

/**
 * Comprehensive cleanup function to remove all auto-generated missed records
 * from both timeAttendance and timeAttendanceRequests collections
 * 
 * This will:
 * 1. Delete all auto-generated "тасалсан" (missed) requests from timeAttendanceRequests
 * 2. Delete all auto-generated records from timeAttendance with Status="тасалсан"
 * 3. Optionally keep or delete records based on query parameters
 * 
 * Query parameters:
 * - dryRun=true : Only count records without deleting
 * - startDate=YYYY-MM-DD : Only delete records from this date onwards
 * - endDate=YYYY-MM-DD : Only delete records up to this date
 */
exports.clearAutoGeneratedRecords = functions
  .region("asia-east2")
  .runWith({ timeoutSeconds: 540, memory: "1GB" })
  .https.onRequest(async (req, res) => {
    // Enable CORS
    res.set('Access-Control-Allow-Origin', '*');
    res.set('Access-Control-Allow-Methods', 'GET, POST, OPTIONS');
    res.set('Access-Control-Allow-Headers', 'Content-Type');
    
    if (req.method === 'OPTIONS') {
      return res.status(200).send();
    }

    try {
      const db = admin.firestore();
      
      // Parse query parameters
      const dryRun = req.query.dryRun === 'true';
      const startDate = req.query.startDate || null;
      const endDate = req.query.endDate || null;
      
      console.log(`Starting cleanup of auto-generated records...`);
      console.log(`Mode: ${dryRun ? 'DRY RUN (no deletions)' : 'PRODUCTION (will delete)'}`);
      console.log(`Date range: ${startDate || 'any'} to ${endDate || 'any'}`);
      
      // ========== STEP 1: Clear from timeAttendanceRequests ==========
      console.log('\n========== Clearing timeAttendanceRequests ==========');
      
      let requestsQuery = db.collection("timeAttendanceRequests")
        .where("AutoGenerated", "==", true);
      
      // Apply date filters if provided
      if (startDate) {
        requestsQuery = requestsQuery.where("Day", ">=", startDate);
      }
      if (endDate) {
        requestsQuery = requestsQuery.where("Day", "<=", endDate);
      }
      
      const requestsSnapshot = await requestsQuery.get();
      console.log(`Found ${requestsSnapshot.size} auto-generated requests`);
      
      // Group by status for reporting
      const requestsByStatus = {};
      requestsSnapshot.docs.forEach(doc => {
        const status = doc.data().Status || 'unknown';
        requestsByStatus[status] = (requestsByStatus[status] || 0) + 1;
      });
      console.log('Requests breakdown by status:', requestsByStatus);
      
      let requestsDeleted = 0;
      
      if (!dryRun && requestsSnapshot.size > 0) {
        // Delete in batches
        const batchSize = 500;
        for (let i = 0; i < requestsSnapshot.docs.length; i += batchSize) {
          const batch = db.batch();
          const batchDocs = requestsSnapshot.docs.slice(i, i + batchSize);
          
          batchDocs.forEach(doc => {
            batch.delete(doc.ref);
          });
          
          await batch.commit();
          requestsDeleted += batchDocs.length;
          console.log(`Deleted batch: ${requestsDeleted}/${requestsSnapshot.size} requests`);
        }
      }
      
      // ========== STEP 2: Clear from timeAttendance ==========
      console.log('\n========== Clearing timeAttendance ==========');
      
      let attendanceQuery = db.collection("timeAttendance")
        .where("AutoGenerated", "==", true);
      
      // Apply date filters if provided
      if (startDate) {
        attendanceQuery = attendanceQuery.where("Day", ">=", startDate);
      }
      if (endDate) {
        attendanceQuery = attendanceQuery.where("Day", "<=", endDate);
      }
      
      const attendanceSnapshot = await attendanceQuery.get();
      console.log(`Found ${attendanceSnapshot.size} auto-generated attendance records`);
      
      // Group by status for reporting
      const attendanceByStatus = {};
      attendanceSnapshot.docs.forEach(doc => {
        const status = doc.data().Status || 'unknown';
        attendanceByStatus[status] = (attendanceByStatus[status] || 0) + 1;
      });
      console.log('Attendance breakdown by status:', attendanceByStatus);
      
      let attendanceDeleted = 0;
      
      if (!dryRun && attendanceSnapshot.size > 0) {
        // Delete in batches
        const batchSize = 500;
        for (let i = 0; i < attendanceSnapshot.docs.length; i += batchSize) {
          const batch = db.batch();
          const batchDocs = attendanceSnapshot.docs.slice(i, i + batchSize);
          
          batchDocs.forEach(doc => {
            batch.delete(doc.ref);
          });
          
          await batch.commit();
          attendanceDeleted += batchDocs.length;
          console.log(`Deleted batch: ${attendanceDeleted}/${attendanceSnapshot.size} attendance records`);
        }
      }
      
      // ========== STEP 3: Get sample records for verification ==========
      const sampleRequests = requestsSnapshot.docs.slice(0, 10).map(doc => {
        const data = doc.data();
        return {
          id: doc.id,
          employee: `${data.LastName} ${data.FirstName}`,
          day: data.Day,
          status: data.Status,
          createdAt: data.CreatedAt || data.CheckDate
        };
      });
      
      const sampleAttendance = attendanceSnapshot.docs.slice(0, 10).map(doc => {
        const data = doc.data();
        return {
          id: doc.id,
          employee: `${data.LastName} ${data.FirstName}`,
          day: data.Day,
          status: data.Status,
          checkDate: data.CheckDate
        };
      });
      
      // ========== Final Summary ==========
      const summary = {
        success: true,
        mode: dryRun ? 'DRY RUN' : 'PRODUCTION',
        dateRange: {
          start: startDate || 'any',
          end: endDate || 'any'
        },
        timeAttendanceRequests: {
          found: requestsSnapshot.size,
          deleted: requestsDeleted,
          byStatus: requestsByStatus,
          samples: sampleRequests
        },
        timeAttendance: {
          found: attendanceSnapshot.size,
          deleted: attendanceDeleted,
          byStatus: attendanceByStatus,
          samples: sampleAttendance
        },
        total: {
          found: requestsSnapshot.size + attendanceSnapshot.size,
          deleted: requestsDeleted + attendanceDeleted
        },
        message: dryRun 
          ? `DRY RUN: Would delete ${requestsSnapshot.size + attendanceSnapshot.size} auto-generated records` 
          : `Successfully deleted ${requestsDeleted + attendanceDeleted} auto-generated records`
      };
      
      console.log('\n========== CLEANUP SUMMARY ==========');
      console.log(JSON.stringify(summary, null, 2));
      
      return res.status(200).json(summary);
      
    } catch (error) {
      console.error("Cleanup error:", error);
      return res.status(500).json({
        success: false,
        error: error.message,
        stack: error.stack
      });
    }
  });
