const functions = require("firebase-functions");
const admin = require("firebase-admin");

// Cleanup function to delete records with empty WeekDay
exports.cleanupEmptyWeekDay = functions
  .region("asia-east2")
  .runWith({ timeoutSeconds: 540, memory: "1GB" })
  .https.onRequest(async (req, res) => {
    try {
      const db = admin.firestore();
      
      console.log("Starting cleanup of records with empty WeekDay...");
      
      // Get all timeAttendanceRequests with empty WeekDay (approved and auto-generated)
      const requestsSnapshot = await db.collection('timeAttendanceRequests')
        .get();
      
      const requestsToDelete = [];
      requestsSnapshot.forEach(doc => {
        const data = doc.data();
        const isEmpty = !data.WeekDay || data.WeekDay === '';
        const isApproved = data.status === 'approved';
        const isAutoGenerated = data.AutoGenerated === true;
        
        if (isEmpty && (isApproved || isAutoGenerated)) {
          requestsToDelete.push({
            id: doc.id,
            employee: `${data.LastName || data.EmployeeLastName} ${data.FirstName || data.EmployeeFirstName}`,
            date: data.Day,
            status: data.status,
            autoGenerated: data.AutoGenerated
          });
        }
      });
      
      console.log(`Found ${requestsToDelete.length} requests to delete`);
      
      // Get all timeAttendance with empty WeekDay
      const attendanceSnapshot = await db.collection('timeAttendance')
        .get();
      
      const attendanceToDelete = [];
      attendanceSnapshot.forEach(doc => {
        const data = doc.data();
        const isEmpty = !data.WeekDay || data.WeekDay === '';
        
        if (isEmpty) {
          attendanceToDelete.push({
            id: doc.id,
            employee: `${data.LastName || data.EmployeeLastName} ${data.FirstName || data.EmployeeFirstName}`,
            date: data.Day,
            autoGenerated: data.AutoGenerated
          });
        }
      });
      
      console.log(`Found ${attendanceToDelete.length} approved records to delete`);
      
      // Delete timeAttendanceRequests in batches
      let deletedRequests = 0;
      const batchSize = 500;
      
      for (let i = 0; i < requestsToDelete.length; i += batchSize) {
        const batch = db.batch();
        const batchItems = requestsToDelete.slice(i, i + batchSize);
        
        batchItems.forEach(item => {
          const docRef = db.collection('timeAttendanceRequests').doc(item.id);
          batch.delete(docRef);
        });
        
        await batch.commit();
        deletedRequests += batchItems.length;
        console.log(`Deleted requests batch: ${deletedRequests}/${requestsToDelete.length}`);
      }
      
      // Delete timeAttendance in batches
      let deletedAttendance = 0;
      
      for (let i = 0; i < attendanceToDelete.length; i += batchSize) {
        const batch = db.batch();
        const batchItems = attendanceToDelete.slice(i, i + batchSize);
        
        batchItems.forEach(item => {
          const docRef = db.collection('timeAttendance').doc(item.id);
          batch.delete(docRef);
        });
        
        await batch.commit();
        deletedAttendance += batchItems.length;
        console.log(`Deleted attendance batch: ${deletedAttendance}/${attendanceToDelete.length}`);
      }
      
      res.json({
        success: true,
        message: `Cleanup completed: deleted ${deletedRequests} requests and ${deletedAttendance} approved records`,
        deletedRequests,
        deletedAttendance,
        totalDeleted: deletedRequests + deletedAttendance,
        requestsDeleted: requestsToDelete,
        attendanceDeleted: attendanceToDelete
      });

    } catch (error) {
      console.error('Error during cleanup:', error);
      res.status(500).json({
        success: false,
        error: error.message
      });
    }
  });
