const functions = require("firebase-functions");
const admin = require("firebase-admin");

// Cleanup function to delete тасалсан requests where approved attendance exists
exports.cleanupWrongMissedRequests = functions
  .region("asia-east2")
  .runWith({ timeoutSeconds: 540, memory: "1GB" })
  .https.onRequest(async (req, res) => {
    try {
      const db = admin.firestore();
      
      console.log("Starting cleanup of wrong тасалсан requests...");
      
      // Get all тасалсан requests
      const missedRequestsSnapshot = await db.collection('timeAttendanceRequests')
        .where('Status', '==', 'тасалсан')
        .get();
      
      console.log(`Found ${missedRequestsSnapshot.size} тасалсан requests to check`);
      
      // Get all approved attendance records
      const approvedSnapshot = await db.collection('timeAttendance')
        .get();
      
      console.log(`Found ${approvedSnapshot.size} approved attendance records`);
      
      // Build a map of approved attendance: { "LastName_FirstName_YYYY-MM-DD": true }
      const approvedMap = {};
      
      approvedSnapshot.forEach(doc => {
        const data = doc.data();
        const lastName = data.LastName || data.EmployeeLastName;
        const firstName = data.FirstName || data.EmployeeFirstName;
        const day = data.Day || data.Date;
        
        if (lastName && firstName && day) {
          const key = `${lastName}_${firstName}_${day}`;
          approvedMap[key] = true;
        }
      });
      
      console.log(`Built approval map with ${Object.keys(approvedMap).length} entries`);
      
      // Check each тасалсан request
      const toDelete = [];
      const toKeep = [];
      
      missedRequestsSnapshot.forEach(doc => {
        const data = doc.data();
        const lastName = data.LastName || data.EmployeeLastName;
        const firstName = data.FirstName || data.EmployeeFirstName;
        const day = data.Day || data.Date;
        
        if (lastName && firstName && day) {
          const key = `${lastName}_${firstName}_${day}`;
          
          if (approvedMap[key]) {
            // This тасалсан request has a corresponding approved record - should be deleted
            toDelete.push({
              id: doc.id,
              employee: `${lastName} ${firstName}`,
              date: day,
              autoGenerated: data.AutoGenerated
            });
          } else {
            toKeep.push({
              employee: `${lastName} ${firstName}`,
              date: day
            });
          }
        }
      });
      
      console.log(`Found ${toDelete.length} wrong requests to delete, ${toKeep.length} valid requests to keep`);
      
      // Delete the wrong requests in batches
      let deletedCount = 0;
      const batchSize = 500;
      
      for (let i = 0; i < toDelete.length; i += batchSize) {
        const batch = db.batch();
        const batchItems = toDelete.slice(i, i + batchSize);
        
        batchItems.forEach(item => {
          const docRef = db.collection('timeAttendanceRequests').doc(item.id);
          batch.delete(docRef);
        });
        
        await batch.commit();
        deletedCount += batchItems.length;
        console.log(`Deleted batch: ${deletedCount}/${toDelete.length}`);
      }
      
      res.json({
        success: true,
        message: `Cleanup completed: deleted ${deletedCount} wrong тасалсан requests`,
        deleted: deletedCount,
        kept: toKeep.length,
        deletedRecords: toDelete,
        keptRecords: toKeep
      });

    } catch (error) {
      console.error('Error during cleanup:', error);
      res.status(500).json({
        success: false,
        error: error.message
      });
    }
  });
