const functions = require("firebase-functions");
const admin = require("firebase-admin");

// Temporary function to delete all auto-generated requests (wrong ones)
exports.deleteAutoGeneratedRequests = functions
  .region("asia-east2")
  .runWith({ timeoutSeconds: 540, memory: "1GB" })
  .https.onRequest(async (req, res) => {
    try {
      const db = admin.firestore();
      
      // Find all timeAttendanceRequests with AutoGenerated = true
      const snapshot = await db.collection("timeAttendanceRequests")
        .where("AutoGenerated", "==", true)
        .get();
      
      console.log(`Found ${snapshot.size} auto-generated requests to delete`);
      
      if (snapshot.empty) {
        return res.json({
          success: true,
          message: "No auto-generated requests found",
          deleted: 0
        });
      }
      
      // Delete in batches (500 max per batch)
      const batches = [];
      let currentBatch = db.batch();
      let batchCount = 0;
      let totalDeleted = 0;
      
      snapshot.docs.forEach(doc => {
        currentBatch.delete(doc.ref);
        batchCount++;
        totalDeleted++;
        
        if (batchCount >= 500) {
          batches.push(currentBatch.commit());
          currentBatch = db.batch();
          batchCount = 0;
        }
      });
      
      // Commit remaining batch
      if (batchCount > 0) {
        batches.push(currentBatch.commit());
      }
      
      await Promise.all(batches);
      
      console.log(`Deleted ${totalDeleted} auto-generated requests`);
      
      res.json({
        success: true,
        message: `Successfully deleted ${totalDeleted} auto-generated requests`,
        deleted: totalDeleted
      });
      
    } catch (error) {
      console.error("Delete error:", error);
      res.status(500).json({
        success: false,
        error: error.message
      });
    }
  });
