/**
 * Import function triggers from their respective submodules:
 *
 * const {onCall} = require("firebase-functions/v2/https");
 * const {onDocumentWritten} = require("firebase-functions/v2/firestore");
 *
 * See a full list of supported triggers at https://firebase.google.com/docs/functions
 */


// Create and deploy your first functions
// https://firebase.google.com/docs/functions/get-started



exports.onAttendanceApproved = require("./onAttendanceApproved").onAttendanceApproved;
exports.submitAttendance = require("./submitAttendance").submitAttendance;

// Employee functions
exports.syncEmployeesToExcel = require("./syncEmployeesToExcel").syncEmployeesToExcel;
exports.syncFromExcelToFirestore = require("./syncFromExcelToFirestore").syncFromExcelToFirestore;
exports.syncDeletionsFromExcel = require("./syncDeletionsFromExcel").syncDeletionsFromExcel;
exports.manageEmployee = require("./manageEmployee").manageEmployee;
exports.updateExistingUsersWithRoles = require("./updateExistingUsersWithRoles").updateExistingUsersWithRoles;
exports.fixEmployeeRoles = require("./fixEmployeeRoles").fixEmployeeRoles;
exports.checkEmployeeFields = require("./checkEmployeeFields").checkEmployeeFields;
exports.checkExcelHeaders = require("./checkExcelHeaders").checkExcelHeaders;
exports.setSupervisorRoles = require("./setSupervisorRoles").setSupervisorRoles;
exports.checkDuplicateCustomers = require("./checkDuplicateCustomers").checkDuplicateCustomers;
exports.removeDuplicateCustomers = require("./removeDuplicateCustomers").removeDuplicateCustomers;
exports.fixUserRoles = require("./fixUserRoles").fixUserRoles;
exports.syncEmployeeNamesToUsers = require("./syncEmployeeNamesToUsers").syncEmployeeNamesToUsers;

// Customer functions
exports.syncCustomersToExcel = require("./syncCustomersToExcel").syncCustomersToExcel;
exports.syncFromExcelToCustomers = require("./syncFromExcelToCustomers").syncFromExcelToCustomers;
exports.manageCustomer = require("./manageCustomer").manageCustomer;

// Project functions
exports.syncProjectsToExcel = require("./syncProjectsToExcel").syncProjectsToExcel;
exports.syncFromExcelToProjects = require("./syncFromExcelToProjects").syncFromExcelToProjects;
exports.manageProject = require("./manageProject").manageProject;
exports.updateProjectRealHours = require("./updateProjectRealHours").updateProjectRealHours;

// Time Attendance functions
exports.manageTimeAttendanceRequest = require("./manageTimeAttendanceRequest").manageTimeAttendanceRequest;
exports.approveTimeAttendanceRequest = require("./approveTimeAttendanceRequest").approveTimeAttendanceRequest;
exports.syncTimeAttendanceToExcel = require("./syncTimeAttendanceToExcel").syncTimeAttendanceToExcel;
exports.syncFromExcelToTimeAttendance = require("./syncFromExcelToTimeAttendance").syncFromExcelToTimeAttendance;
exports.validateTimeAttendance = require("./validateTimeAttendance").validateTimeAttendance;
exports.markTimeAttendanceStatus = require("./markTimeAttendanceStatus").markTimeAttendanceStatus;
exports.fullSyncExcelToFirestore = require("./fullSyncExcelToFirestore").fullSyncExcelToFirestore;
exports.syncEmployeeNamesToRequests = require("./syncEmployeeNamesToRequests").syncEmployeeNamesToRequests;
// Production scheduled function and test endpoint
exports.scheduledTACheck = require("./scheduledTACheck").scheduledTACheck;
exports.testScheduledTACheck = require("./testScheduledTACheck").testScheduledTACheck;

// One-time utility functions (already executed, kept for reference)
// Uncomment if needed for future use
// exports.migrateEmployeeIDs = require("./migrateEmployeeIDs").migrateEmployeeIDs;
// exports.deleteAutoGeneratedRequests = require("./deleteAutoGeneratedRequests").deleteAutoGeneratedRequests;
// exports.cleanupWrongMissedRequests = require("./cleanupWrongMissedRequests").cleanupWrongMissedRequests;
// exports.cleanupEmptyWeekDay = require("./cleanupEmptyWeekDay").cleanupEmptyWeekDay;
// exports.checkEmployeeRequests = require("./checkEmployeeRequests").checkEmployeeRequests;
// exports.checkDuplicateRequests = require("./checkDuplicateRequests").checkDuplicateRequests;
// exports.checkTimeAttendanceFields = require("./checkTimeAttendanceFields").checkTimeAttendanceFields;

// Cleanup function for duplicate auto-generated missed requests
exports.cleanupDuplicateMissedRequests = require("./cleanupDuplicateMissedRequests").cleanupDuplicateMissedRequests;

// Diagnostic function to check notSynced records
exports.checkNotSyncedRecords = require("./checkNotSyncedRecords").checkNotSyncedRecords;

// Fix function to add missing IDs to timeAttendance records
exports.fixMissingIdsInTimeAttendance = require("./fixMissingIdsInTimeAttendance").fixMissingIdsInTimeAttendance;

// Fix function to add missing FirstName/LastName or IDs by matching with employees
exports.fixTimeAttendanceNames = require("./fixTimeAttendanceNames").fixTimeAttendanceNames;

// Fix function to add missing EmployeeID to timeAttendance records
exports.fixMissingEmployeeID = require("./fixMissingEmployeeID").fixMissingEmployeeID;

// Fix function for Баатархүү records (EmployeeID 40)
exports.fixBaatarkhuu = require("./fixBaatarkhuu").fixBaatarkhuu;

// Fix function for Баатархүү records in timeAttendanceRequests
exports.fixBaatarkhuuRequests = require("./fixBaatarkhuuRequests").fixBaatarkhuuRequests;

// Check function to see current state of Баатархүү records
exports.checkBaatarkhuu = require("./checkBaatarkhuu").checkBaatarkhuu;

// Fix function to update missing FirstName/LastName/EmployeeID in Excel
exports.fixExcelMissingFields = require("./fixExcelMissingFields").fixExcelMissingFields;

// Helper functions
exports.listExcelTables = require("./listExcelTables").listExcelTables;
exports.findExcelFile = require("./findExcelFile").findExcelFile;
