const functions = require("firebase-functions");
const { initializeApp } = require("firebase-admin/app");
const { getFirestore } = require("firebase-admin/firestore");

// Initialize Firebase Admin (if not already initialized)
try {
  initializeApp();
} catch (e) {
  // Already initialized
}

const db = getFirestore();

/**
 * Scheduled Cloud Function that runs on 15th and last day of every month
 * Checks each working day to see if employees have time attendance requests
 * Creates "тасалсан" (missed work) requests for missing days
 * 
 * Schedule: Runs on 15th and last day of each month at 11:00 PM Mongolia time
 */
exports.scheduledTACheck = functions
  .region('asia-east2')
  .pubsub.schedule('0 23 15,28-31 * *') // 11 PM on 15th and days 28-31
  .timeZone('Asia/Ulaanbaatar')
  .onRun(async (context) => {
    console.log('Starting scheduled TA check...');
    
    try {
      const now = new Date();
      const year = now.getFullYear();
      const month = now.getMonth() + 1; // 1-12
      const day = now.getDate();
      const lastDayOfMonth = new Date(year, month, 0).getDate();
      
      // Only run on 15th or last day of month
      if (day !== 15 && day !== lastDayOfMonth) {
        console.log(`Today is ${day}, not 15th or last day (${lastDayOfMonth}). Skipping.`);
        return null;
      }
      
      console.log(`Running check for ${year}-${month}-${day}`);
      
      // Get all active employees (excluding Supervisor and nonEmployee roles)
      const employeesSnapshot = await db.collection('employees')
        .where('State', '==', 'Ажиллаж байгаа')
        .get();
      
      // Filter out Supervisor and nonEmployee roles
      const activeEmployees = [];
      employeesSnapshot.forEach(doc => {
        const emp = doc.data();
        if (emp.Role !== 'Supervisor' && emp.Role !== 'nonEmployee') {
          activeEmployees.push({ id: doc.id, ...emp });
        }
      });
      
      console.log(`Found ${employeesSnapshot.size} active employees, ${activeEmployees.length} need TA tracking`);
      
      // Determine which days to check (1st to today OR 1st to 15th)
      const checkUntilDay = day === 15 ? 15 : lastDayOfMonth;
      
      // Define date range for filtering
      const startDate = `${year}-${String(month).padStart(2, '0')}-01`;
      const endDate = `${year}-${String(month).padStart(2, '0')}-${String(checkUntilDay).padStart(2, '0')}`;
      
      console.log(`Checking period: ${startDate} to ${endDate}`);
      
      // Get time attendance requests for this month only
      const taRequestsSnapshot = await db.collection('timeAttendanceRequests')
        .where('Day', '>=', startDate)
        .where('Day', '<=', endDate)
        .get();
      
      // Get approved time attendance records for this month only
      const taApprovedSnapshot = await db.collection('timeAttendance')
        .where('Day', '>=', startDate)
        .where('Day', '<=', endDate)
        .get();
      
      console.log(`Found ${taRequestsSnapshot.size} TA requests and ${taApprovedSnapshot.size} approved records for this period`);
      
      // Build a map of employee attendance by day: { employeeId: { 'YYYY-MM-DD': true } }
      const attendanceMap = {};
      
      // Add only NON-auto-generated requests (real employee requests)
      taRequestsSnapshot.forEach(doc => {
        const data = doc.data();
        
        // Skip auto-generated requests - we only care about real employee submissions
        if (data.AutoGenerated === true) {
          return;
        }
        
        const employeeKey = `${data.LastName}_${data.FirstName}`;
        const day = data.Day;
        
        if (!attendanceMap[employeeKey]) {
          attendanceMap[employeeKey] = {};
        }
        attendanceMap[employeeKey][day] = true;
      });
      
      // Add all approved records
      taApprovedSnapshot.forEach(doc => {
        const data = doc.data();
        // Handle both field name patterns
        const lastName = data.LastName || data.EmployeeLastName;
        const firstName = data.FirstName || data.EmployeeFirstName;
        const employeeKey = `${lastName}_${firstName}`;
        const day = data.Day || data.Date;
        
        if (lastName && firstName && day) {
          if (!attendanceMap[employeeKey]) {
            attendanceMap[employeeKey] = {};
          }
          attendanceMap[employeeKey][day] = true;
        }
      });
      
      console.log(`Built attendance map for ${Object.keys(attendanceMap).length} employees`);
      
      // Filter employees to only those needing TA tracking (exclude Supervisor and nonEmployee)
      const employeesToCheck = [];
      for (const doc of employeesSnapshot.docs) {
        const emp = doc.data();
        if (emp.Role !== 'Supervisor' && emp.Role !== 'nonEmployee') {
          employeesToCheck.push(emp);
        }
      }
      
      console.log(`Found ${employeesSnapshot.size} active employees, ${employeesToCheck.length} need TA tracking`);
      
      // Check each employee for each working day
      const batch = db.batch();
      let createdCount = 0;
      const missingRecords = [];
      
      for (const employee of employeesToCheck) {
        const firstName = employee.FirstName;
        const lastName = employee.LastName;
        const employeeId = employee.Id || employee.NumID;
        const employeeKey = `${lastName}_${firstName}`;
        
        // Check each day from 1st to checkUntilDay
        for (let d = 1; d <= checkUntilDay; d++) {
          const checkDate = `${year}-${String(month).padStart(2, '0')}-${String(d).padStart(2, '0')}`;
          const dateObj = new Date(year, month - 1, d);
          const dayOfWeek = dateObj.getDay();
          
          // Skip weekends (0 = Sunday, 6 = Saturday)
          if (dayOfWeek === 0 || dayOfWeek === 6) {
            continue;
          }
          
          // Check if employee has attendance for this day
          const hasAttendance = attendanceMap[employeeKey] && attendanceMap[employeeKey][checkDate];
          
          if (!hasAttendance) {
            console.log(`Missing: ${lastName} ${firstName} on ${checkDate}`);
            
            // Get day of week name
            const weekDays = ['Ням', 'Даваа', 'Мягмар', 'Лхагва', 'Пүрэв', 'Баасан', 'Бямба'];
            const weekDay = weekDays[dayOfWeek];
            
            const newRequestRef = db.collection('timeAttendanceRequests').doc();
            const requestData = {
              EmployeeID: employeeId,
              FirstName: firstName,
              LastName: lastName,
              Day: checkDate,
              WeekDay: weekDay,
              Status: 'тасалсан',
              WorkingHour: 8,
              ProjectID: 'N/A',
              Detail: `Автоматаар үүсгэсэн - ${day === 15 ? '15-ны' : 'сарын сүүлийн өдрийн'} шалгалт`,
              Comment: 'Ирээгүй',
              CreatedAt: new Date().toISOString(),
              AutoGenerated: true,
              CheckDate: `${year}-${month}-${day}`,
              status: 'pending' // Needs supervisor approval
            };
            
            batch.set(newRequestRef, requestData);
            createdCount++;
            missingRecords.push({ employee: `${lastName} ${firstName}`, date: checkDate });
          }
        }
      }
      
      // Commit the batch
      if (createdCount > 0) {
        await batch.commit();
        console.log(`✓ Created ${createdCount} "тасалсан" requests for approval`);
      } else {
        console.log('No missing attendance found - all employees have records');
      }
      
      // Return summary
      return {
        success: true,
        date: `${year}-${month}-${day}`,
        checkPeriod: `${year}-${month}-01 to ${year}-${month}-${checkUntilDay}`,
        totalEmployees: employeesSnapshot.size,
        workingDaysChecked: checkUntilDay,
        createdRequests: createdCount,
        missingRecords: missingRecords.slice(0, 10), // First 10 for logging
        message: `Scheduled TA check completed. Created ${createdCount} "тасалсан" requests for supervisor approval.`
      };
      
    } catch (error) {
      console.error('Error in scheduled TA check:', error);
      throw error;
    }
  });
