const functions = require("firebase-functions");
const { initializeApp } = require("firebase-admin/app");
const { getFirestore } = require("firebase-admin/firestore");

// Initialize Firebase Admin (if not already initialized)
try {
  initializeApp();
} catch (e) {
  // Already initialized
}

const db = getFirestore();

/**
 * TEST VERSION - HTTP Cloud Function to test the scheduled TA check logic
 * Can be called manually to test without waiting for the schedule
 * 
 * Usage: GET/POST to the function URL
 */
exports.testScheduledTACheck = functions
  .region('asia-east2')
  .https.onRequest(async (req, res) => {
    // Enable CORS
    res.set('Access-Control-Allow-Origin', '*');
    res.set('Access-Control-Allow-Methods', 'GET, POST, OPTIONS');
    res.set('Access-Control-Allow-Headers', 'Content-Type');
    
    if (req.method === 'OPTIONS') {
      return res.status(200).send();
    }
    
    console.log('Starting TEST scheduled TA check...');
    
    try {
      const productionMode = req.query.production === 'true';
      const now = new Date();
      const year = now.getFullYear();
      const month = now.getMonth() + 1; // 1-12
      const day = now.getDate();
      const lastDayOfMonth = new Date(year, month, 0).getDate();
      
      console.log(`Testing check for ${year}-${month}-${day}`);
      
      // Get all active employees
      const employeesSnapshot = await db.collection('employees')
        .where('State', '==', 'Ажиллаж байгаа')
        .get();
      
      console.log(`Found ${employeesSnapshot.size} active employees`);
      
      // Determine which days to check (1st to today)
      const checkUntilDay = day;
      
      // Define date range for filtering
      const startDate = `${year}-${String(month).padStart(2, '0')}-01`;
      const endDate = `${year}-${String(month).padStart(2, '0')}-${String(checkUntilDay).padStart(2, '0')}`;
      
      console.log(`Checking period: ${startDate} to ${endDate}`);
      
      // Get time attendance requests for this month only
      const taRequestsSnapshot = await db.collection('timeAttendanceRequests')
        .where('Day', '>=', startDate)
        .where('Day', '<=', endDate)
        .get();
      
      // Also get approved time attendance records for this month only
      const taApprovedSnapshot = await db.collection('timeAttendance')
        .where('Day', '>=', startDate)
        .where('Day', '<=', endDate)
        .get();
      
      console.log(`Found ${taRequestsSnapshot.size} TA requests and ${taApprovedSnapshot.size} approved records for this period`);
      
      // Build a map of employee attendance by day: { employeeId: { 'YYYY-MM-DD': true } }
      const attendanceMap = {};
      
      // Add only NON-auto-generated requests (real employee requests)
      taRequestsSnapshot.forEach(doc => {
        const data = doc.data();
        
        // Skip auto-generated requests - we only care about real employee submissions
        if (data.AutoGenerated === true) {
          return;
        }
        
        const employeeKey = `${data.LastName}_${data.FirstName}`;
        const day = data.Day;
        
        if (!attendanceMap[employeeKey]) {
          attendanceMap[employeeKey] = {};
        }
        attendanceMap[employeeKey][day] = true;
      });
      
      // Add all approved records
      taApprovedSnapshot.forEach(doc => {
        const data = doc.data();
        // Handle both field name patterns
        const lastName = data.LastName || data.EmployeeLastName;
        const firstName = data.FirstName || data.EmployeeFirstName;
        const employeeKey = `${lastName}_${firstName}`;
        const day = data.Day || data.Date;
        
        if (lastName && firstName && day) {
          if (!attendanceMap[employeeKey]) {
            attendanceMap[employeeKey] = {};
          }
          attendanceMap[employeeKey][day] = true;
        }
      });
      
      console.log(`Built attendance map for ${Object.keys(attendanceMap).length} employees`);
      
      // Filter employees to only those needing TA tracking (exclude Supervisor and nonEmployee)
      const employeesToCheck = [];
      for (const doc of employeesSnapshot.docs) {
        const emp = doc.data();
        if (emp.Role !== 'Supervisor' && emp.Role !== 'nonEmployee') {
          employeesToCheck.push(emp);
        }
      }
      
      console.log(`Found ${employeesSnapshot.size} active employees, ${employeesToCheck.length} need TA tracking`);
      
      // Check each employee for each working day
      const batch = db.batch();
      let createdCount = 0;
      const missingRecords = [];
      
      for (const employee of employeesToCheck) {
        const firstName = employee.FirstName;
        const lastName = employee.LastName;
        const employeeId = employee.Id || employee.NumID;
        const employeeKey = `${lastName}_${firstName}`;
        
        // Check each day from 1st to checkUntilDay
        for (let d = 1; d <= checkUntilDay; d++) {
          const checkDate = `${year}-${String(month).padStart(2, '0')}-${String(d).padStart(2, '0')}`;
          const dateObj = new Date(year, month - 1, d);
          const dayOfWeek = dateObj.getDay();
          
          // Skip weekends (0 = Sunday, 6 = Saturday)
          if (dayOfWeek === 0 || dayOfWeek === 6) {
            continue;
          }
          
          // Check if employee has attendance for this day
          const hasAttendance = attendanceMap[employeeKey] && attendanceMap[employeeKey][checkDate];
          
          if (!hasAttendance) {
            console.log(`Missing: ${lastName} ${firstName} on ${checkDate}`);
            
            // Get day of week name
            const weekDays = ['Ням', 'Даваа', 'Мягмар', 'Лхагва', 'Пүрэв', 'Баасан', 'Бямба'];
            const weekDay = weekDays[dayOfWeek];
            
            const newRequestRef = db.collection('timeAttendanceRequests').doc();
            const requestData = {
              EmployeeID: employeeId,
              FirstName: firstName,
              LastName: lastName,
              Day: checkDate,
              WeekDay: weekDay,
              Status: 'тасалсан',
              WorkingHour: 8,
              ProjectID: 'N/A',
              Detail: `Автоматаар үүсгэсэн - TEST шалгалт`,
              Comment: 'Ирээгүй',
              CreatedAt: new Date().toISOString(),
              AutoGenerated: true,
              TestRun: true,
              CheckDate: `${year}-${month}-${day}`,
              status: 'pending' // Needs supervisor approval
            };
            
            batch.set(newRequestRef, requestData);
            createdCount++;
            missingRecords.push({ employee: `${lastName} ${firstName}`, date: checkDate, employeeId });
          }
        }
      }
      
      // Commit the batch
      if (createdCount > 0) {
        if (productionMode) {
          await batch.commit();
          console.log(`✓ PRODUCTION MODE: Created ${createdCount} "тасалсан" requests in database`);
        } else {
          console.log(`✓ TEST MODE: Would create ${createdCount} "тасалсан" requests (not saved)`);
        }
      } else {
        console.log('No missing requests found - all employees have TA records');
      }
      
      // Return detailed summary
      const result = {
        success: true,
        testMode: !productionMode,
        productionMode: productionMode,
        date: `${year}-${month}-${day}`,
        checkPeriod: `${year}-${month}-01 to ${year}-${month}-${checkUntilDay}`,
        totalEmployees: employeesSnapshot.size,
        workingDaysChecked: checkUntilDay,
        createdRequests: createdCount,
        missingRecords: missingRecords,
        message: `TEST: Created ${createdCount} "тасалсан" requests for employees with missing attendance days.`
      };
      
      res.status(200).json(result);
      
    } catch (error) {
      console.error('Error in TEST scheduled TA check:', error);
      res.status(500).json({
        error: 'Internal server error',
        message: error.message,
        stack: error.stack
      });
    }
  });
