// File generated by FlutterFire CLI — DO NOT EDIT MANUALLY
// To regenerate: flutterfire configure

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        return android;
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCizwhrXubtiUaasWh8y-9u-plTltyT3v0',
    appId: '1:168681350058:web:a6f34f9e5ee6362b2e01d3',
    messagingSenderId: '168681350058',
    projectId: 'munkh-zaisan',
    authDomain: 'munkh-zaisan.firebaseapp.com',
    storageBucket: 'munkh-zaisan.firebasestorage.app',
    measurementId: 'G-BEWRJ14YC5',
  );

  // TODO: Replace with your android/google-services.json values

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMIYV4_rIN1DDowH4JFLvIzXKj1bNJTWo',
    appId: '1:168681350058:android:184c9a5386baab0a2e01d3',
    messagingSenderId: '168681350058',
    projectId: 'munkh-zaisan',
    storageBucket: 'munkh-zaisan.firebasestorage.app',
  );

  // Run: flutterfire configure --project=munkh-zaisan

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOHoX9g0qzvTNNhpoO3rBNAlQsSZ5iHws',
    appId: '1:168681350058:ios:6279996d12e558c72e01d3',
    messagingSenderId: '168681350058',
    projectId: 'munkh-zaisan',
    storageBucket: 'munkh-zaisan.firebasestorage.app',
    iosClientId: '168681350058-ukt4k8tvt31bcmqumndrvftima8o9igs.apps.googleusercontent.com',
    iosBundleId: 'com.munkhzaisan.munkhzaisanMobile',
  );

  // TODO: Replace with your ios/GoogleService-Info.plist values
}